spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5433/eCommerce-inventory
    username: inventory-user
    password: inventory123
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update